USE [master]
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'LiaNcc')
BEGIN
    CREATE DATABASE [LiaNcc]
END
GO

USE [LiaNcc]
GO

-- USERS & ROLES

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Users PRIMARY KEY DEFAULT NEWID(),
    FullName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

CREATE UNIQUE INDEX IX_Users_Email ON Users(Email);
GO

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Roles PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Roles_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Roles_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

CREATE UNIQUE INDEX IX_Roles_Name ON Roles(Name);
GO

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    AssignedAt DATETIME2 NOT NULL CONSTRAINT DF_UserRoles_AssignedAt DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId),

    CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId)
        REFERENCES Users(Id)
        ON DELETE CASCADE,

    CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId)
        REFERENCES Roles(Id)
        ON DELETE CASCADE
);
GO

CREATE INDEX IX_UserRoles_UserId ON UserRoles(UserId);
CREATE INDEX IX_UserRoles_RoleId ON UserRoles(RoleId);
GO

-- LOCALIZATION

CREATE TABLE Languages (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Languages PRIMARY KEY DEFAULT NEWID(),
    Code NVARCHAR(10) NOT NULL, -- e.g., 'it', 'en'
    Name NVARCHAR(50) NOT NULL,
    IsDefault BIT NOT NULL CONSTRAINT DF_Languages_IsDefault DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_Languages_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Languages_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO
CREATE UNIQUE INDEX IX_Languages_Code ON Languages(Code);
GO

CREATE TABLE LocalizedContents (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LocalizedContents PRIMARY KEY DEFAULT NEWID(),
    EntityName NVARCHAR(100) NOT NULL, -- e.g., 'Tours', 'SitePages', 'Static'
    EntityId UNIQUEIDENTIFIER NULL,
    ContentKey NVARCHAR(100) NOT NULL, -- e.g., 'Title', 'Description'
    LanguageCode NVARCHAR(10) NOT NULL,
    ContentValue NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_LocalizedContents_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_LocalizedContents_Languages FOREIGN KEY (LanguageCode) REFERENCES Languages(Code) ON DELETE CASCADE
);
GO
CREATE INDEX IX_LocalizedContents_Entity ON LocalizedContents(EntityName, EntityId, LanguageCode, ContentKey);
GO

-- CMS (SitePages, PageSections, CallToActions)

CREATE TABLE SitePages (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SitePages PRIMARY KEY DEFAULT NEWID(),
    Slug NVARCHAR(100) NOT NULL, -- e.g., 'home', 'fleet'
    Name NVARCHAR(100) NOT NULL,
    MetaTitle NVARCHAR(200) NULL,
    MetaDescription NVARCHAR(500) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_SitePages_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_SitePages_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO
CREATE UNIQUE INDEX IX_SitePages_Slug ON SitePages(Slug);
GO

CREATE TABLE PageSections (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PageSections PRIMARY KEY DEFAULT NEWID(),
    PageId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Title NVARCHAR(200) NULL,
    Description NVARCHAR(MAX) NULL,
    ImageUrl NVARCHAR(1000) NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_PageSections_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_PageSections_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_PageSections_SitePages FOREIGN KEY (PageId) REFERENCES SitePages(Id) ON DELETE CASCADE
);
GO

CREATE TABLE CallToActions (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CallToActions PRIMARY KEY DEFAULT NEWID(),
    PageId UNIQUEIDENTIFIER NULL,
    SectionId UNIQUEIDENTIFIER NULL,
    Label NVARCHAR(100) NULL,
    Title NVARCHAR(200) NULL,
    Url NVARCHAR(500) NULL,
    Action NVARCHAR(100) NULL,
    Controller NVARCHAR(100) NULL,
    VisualStyle NVARCHAR(50) NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_CallToActions_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_CallToActions_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_CallToActions_SitePages FOREIGN KEY (PageId) REFERENCES SitePages(Id),
    CONSTRAINT FK_CallToActions_PageSections FOREIGN KEY (SectionId) REFERENCES PageSections(Id)
);
GO

-- MEDIA

CREATE TABLE MediaAssets (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_MediaAssets PRIMARY KEY DEFAULT NEWID(),
    FileName NVARCHAR(255) NOT NULL,
    FileUrl NVARCHAR(1000) NOT NULL,
    MimeType NVARCHAR(50) NOT NULL,
    FileSize INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_MediaAssets_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE EntityMedia (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_EntityMedia PRIMARY KEY DEFAULT NEWID(),
    EntityName NVARCHAR(100) NOT NULL,
    EntityId UNIQUEIDENTIFIER NOT NULL,
    MediaAssetId UNIQUEIDENTIFIER NOT NULL,
    MediaType NVARCHAR(50) NOT NULL, -- e.g., 'Gallery', 'Featured'
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_EntityMedia_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_EntityMedia_MediaAssets FOREIGN KEY (MediaAssetId) REFERENCES MediaAssets(Id) ON DELETE CASCADE
);
GO
CREATE INDEX IX_EntityMedia_Entity ON EntityMedia(EntityName, EntityId);
GO

-- SERVICES

CREATE TABLE Services (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Services PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Icon NVARCHAR(50) NULL,
    CoverImageUrl NVARCHAR(1000) NULL,
    IsFeatured BIT NOT NULL CONSTRAINT DF_Services_IsFeatured DEFAULT 0,
    IsBookable BIT NOT NULL CONSTRAINT DF_Services_IsBookable DEFAULT 1,
    IsActive BIT NOT NULL CONSTRAINT DF_Services_IsActive DEFAULT 1,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Services_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

-- VEHICLES

CREATE TABLE VehicleCategories (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_VehicleCategories PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_VehicleCategories_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_VehicleCategories_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

CREATE TABLE Vehicles (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Vehicles PRIMARY KEY DEFAULT NEWID(),
    CategoryId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Title NVARCHAR(200) NULL,
    Description NVARCHAR(MAX) NULL,
    Seats INT NOT NULL,
    Luggages INT NOT NULL,
    IsFeatured BIT NOT NULL CONSTRAINT DF_Vehicles_IsFeatured DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_Vehicles_IsActive DEFAULT 1,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Vehicles_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Vehicles_VehicleCategories FOREIGN KEY (CategoryId) REFERENCES VehicleCategories(Id) ON DELETE CASCADE
);
GO

CREATE TABLE VehicleFeatures (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_VehicleFeatures PRIMARY KEY DEFAULT NEWID(),
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Icon NVARCHAR(50) NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_VehicleFeatures_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_VehicleFeatures_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id) ON DELETE CASCADE
);
GO

-- TOURS

CREATE TABLE TourCategories (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TourCategories PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_TourCategories_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TourCategories_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

CREATE TABLE Tours (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Tours PRIMARY KEY DEFAULT NEWID(),
    CategoryId UNIQUEIDENTIFIER NULL,
    Name NVARCHAR(150) NOT NULL,
    Slug NVARCHAR(150) NOT NULL,
    Price DECIMAL(18,2) NULL,
    CoverImageUrl NVARCHAR(1000) NULL,
    Description NVARCHAR(MAX) NULL,
    HeroTitle NVARCHAR(200) NULL,
    HeroSubtitle NVARCHAR(500) NULL,
    ExperienceDescription NVARCHAR(MAX) NULL,
    ExperienceImageUrl NVARCHAR(1000) NULL,
    DurationDays INT NULL,
    DurationHours INT NULL,
    MeetingPoint NVARCHAR(500) NULL,
    VehicleId UNIQUEIDENTIFIER NULL,
    IsFeatured BIT NOT NULL CONSTRAINT DF_Tours_IsFeatured DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_Tours_IsActive DEFAULT 1,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tours_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Tours_TourCategories FOREIGN KEY (CategoryId) REFERENCES TourCategories(Id)
);
GO
CREATE UNIQUE INDEX IX_Tours_Slug ON Tours(Slug);
GO

CREATE TABLE TourSections (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TourSections PRIMARY KEY DEFAULT NEWID(),
    TourId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TourSections_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_TourSections_Tours FOREIGN KEY (TourId) REFERENCES Tours(Id) ON DELETE CASCADE
);
GO

CREATE TABLE TourGalleryImages (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TourGalleryImages PRIMARY KEY DEFAULT NEWID(),
    TourId UNIQUEIDENTIFIER NOT NULL,
    ImageUrl NVARCHAR(1000) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TourGalleryImages_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TourGalleryImages_Tours FOREIGN KEY (TourId) REFERENCES Tours(Id) ON DELETE CASCADE
);
GO

CREATE TABLE TourInfoItems (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TourInfoItems PRIMARY KEY DEFAULT NEWID(),
    TourId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Icon NVARCHAR(50) NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TourInfoItems_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TourInfoItems_Tours FOREIGN KEY (TourId) REFERENCES Tours(Id) ON DELETE CASCADE
);
GO

-- BOOKINGS

CREATE TABLE BookingServiceTypes (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BookingServiceTypes PRIMARY KEY DEFAULT NEWID(),
    Code NVARCHAR(50) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_BookingServiceTypes_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_BookingServiceTypes_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO
CREATE UNIQUE INDEX IX_BookingServiceTypes_Code ON BookingServiceTypes(Code);
GO

CREATE TABLE BookingPassengerOptions (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BookingPassengerOptions PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL CONSTRAINT DF_BookingPassengerOptions_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_BookingPassengerOptions_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE Bookings (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Bookings PRIMARY KEY DEFAULT NEWID(),
    FullName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    Phone NVARCHAR(50) NULL,
    ServiceDate DATETIME2 NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NULL,
    PassengerOptionId UNIQUEIDENTIFIER NULL,
    TourId UNIQUEIDENTIFIER NULL,
    VehicleId UNIQUEIDENTIFIER NULL,
    Message NVARCHAR(MAX) NULL,
    Status NVARCHAR(50) NOT NULL CONSTRAINT DF_Bookings_Status DEFAULT 'Pending',
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Bookings_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Bookings_ServiceTypes FOREIGN KEY (ServiceTypeId) REFERENCES BookingServiceTypes(Id),
    CONSTRAINT FK_Bookings_PassengerOptions FOREIGN KEY (PassengerOptionId) REFERENCES BookingPassengerOptions(Id),
    CONSTRAINT FK_Bookings_Tours FOREIGN KEY (TourId) REFERENCES Tours(Id),
    CONSTRAINT FK_Bookings_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id)
);
GO

-- CONTACT MESSAGES
-- (Already handled above, but redefining for completeness if needed)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ContactMessages]') AND type in (N'U'))
BEGIN
CREATE TABLE ContactMessages (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ContactMessages PRIMARY KEY DEFAULT NEWID(),
    FullName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    IsRead BIT NOT NULL CONSTRAINT DF_ContactMessages_IsRead DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_ContactMessages_CreatedAt DEFAULT SYSUTCDATETIME()
);
END
GO

-- COMPANY

CREATE TABLE CompanyProfile (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CompanyProfile PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    VatNumber NVARCHAR(50) NULL,
    Address NVARCHAR(500) NULL,
    City NVARCHAR(100) NULL,
    ZipCode NVARCHAR(20) NULL,
    Country NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_CompanyProfile_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

CREATE TABLE CompanyContacts (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CompanyContacts PRIMARY KEY DEFAULT NEWID(),
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    Type NVARCHAR(50) NOT NULL, -- e.g., 'Email', 'Phone'
    Value NVARCHAR(256) NOT NULL,
    IsPrimary BIT NOT NULL CONSTRAINT DF_CompanyContacts_IsPrimary DEFAULT 0,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_CompanyContacts_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_CompanyContacts_CompanyProfile FOREIGN KEY (CompanyId) REFERENCES CompanyProfile(Id) ON DELETE CASCADE
);
GO

-- PARTNERS

CREATE TABLE Partners (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Partners PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    WebsiteUrl NVARCHAR(500) NULL,
    LogoUrl NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Partners_IsActive DEFAULT 1,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Partners_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);
GO

-- INITIAL SEED (ROLES & LANGUAGES)
INSERT INTO Roles (Id, Name, Description)
VALUES
('E3452BAA-93B4-4B36-A309-8C7E7BC4B692', 'Admin', 'Administrator role with full access'),
('C996ED9E-C6B3-4412-B67D-51B42E708E5B', 'Operator', 'Operator role with operational access'),
('F07A3E76-13E0-4D88-8869-2E82EBC8234E', 'User', 'Standard user role');

INSERT INTO Languages (Id, Code, Name, IsDefault)
VALUES
(NEWID(), 'it', 'Italiano', 1),
(NEWID(), 'en', 'English', 0);
GO
