//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiaNcc.FE.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TourDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TourDetail() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiaNcc.FE.Resources.Views.Home.TourDetail", typeof(TourDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter any special requests....
        /// </summary>
        public static string AdditionalRequests {
            get {
                return ResourceManager.GetString("AdditionalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Back to tours.
        /// </summary>
        public static string BackToTours {
            get {
                return ResourceManager.GetString("BackToTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fill out the form to receive an immediate personalized quote..
        /// </summary>
        public static string BookingDescription {
            get {
                return ResourceManager.GetString("BookingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Booking Request.
        /// </summary>
        public static string BookingRequest {
            get {
                return ResourceManager.GetString("BookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a dd/mm/yyyy.
        /// </summary>
        public static string DatePlaceholder {
            get {
                return ResourceManager.GetString("DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pick-up at hotel or private residence.
        /// </summary>
        public static string DefaultMeetingPoint {
            get {
                return ResourceManager.GetString("DefaultMeetingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mercedes-Benz S-Class or V-Class Luxury.
        /// </summary>
        public static string DefaultVehicle {
            get {
                return ResourceManager.GetString("DefaultVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Desired Date.
        /// </summary>
        public static string DesiredDate {
            get {
                return ResourceManager.GetString("DesiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emotional Gallery.
        /// </summary>
        public static string EmotionalGallery {
            get {
                return ResourceManager.GetString("EmotionalGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Experience.
        /// </summary>
        public static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full day.
        /// </summary>
        public static string FullDay {
            get {
                return ResourceManager.GetString("FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number of Guests.
        /// </summary>
        public static string GuestsNumber {
            get {
                return ResourceManager.GetString("GuestsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Meeting Point.
        /// </summary>
        public static string MeetingPoint {
            get {
                return ResourceManager.GetString("MeetingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (optional).
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Price per person.
        /// </summary>
        public static string PricePerPerson {
            get {
                return ResourceManager.GetString("PricePerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N/A.
        /// </summary>
        public static string PriceUnavailable {
            get {
                return ResourceManager.GetString("PriceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while sending the booking request. Please try again..
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Request sent successfully!.
        /// </summary>
        public static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a john@example.com.
        /// </summary>
        public static string SampleEmail {
            get {
                return ResourceManager.GetString("SampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a John Doe.
        /// </summary>
        public static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select number of guests.
        /// </summary>
        public static string SelectGuests {
            get {
                return ResourceManager.GetString("SelectGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select the number of guests..
        /// </summary>
        public static string SelectGuestsError {
            get {
                return ResourceManager.GetString("SelectGuestsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Booking Request.
        /// </summary>
        public static string SendBookingRequest {
            get {
                return ResourceManager.GetString("SendBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SENDING....
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tour Detail.
        /// </summary>
        public static string TourDetailTitle {
            get {
                return ResourceManager.GetString("TourDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tour not found.
        /// </summary>
        public static string TourNotFound {
            get {
                return ResourceManager.GetString("TourNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trip details.
        /// </summary>
        public static string TripDetails {
            get {
                return ResourceManager.GetString("TripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visual Portfolio.
        /// </summary>
        public static string VisualPortfolio {
            get {
                return ResourceManager.GetString("VisualPortfolio", resourceCulture);
            }
        }
    }
}
